name: Build and Pack .NET Global Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Manual Run
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Restore dependencies
        run: dotnet restore Scanner/Scanner.slnx
      - name: Build
        run: dotnet build Scanner/Scanner.slnx --configuration Release --no-restore
      - name: Test
        run: dotnet test Scanner/Scanner.slnx --no-build --verbosity normal
      - name: Copy root README.md to Scanner.Cli
        run: cp README.md Scanner/Scanner.Cli/README.md

      - name: Pack CLI as .NET Tool
        run: dotnet pack Scanner/Scanner.Cli/Scanner.Cli.csproj --configuration Release --output ../artifacts --no-build
      - name: Upload .nupkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: PutridParrot.Scanner.Cli
          path: /home/runner/work/PlatformScan/artifacts/PutridParrot.Scanner.*.nupkg
      - name: Publish .nupkg to NuGet.org
        run: dotnet nuget push /home/runner/work/PlatformScan/artifacts/PutridParrot.Scanner.*.nupkg  --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
